# NOTE: Activate 2 nodes in parallel on CircleCI
version: 2
jobs:
  "docker-release":
    docker:
    - image: docker
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: build and publish docker image
        command: |
          printf 'y' | docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
          docker build -t hypnosapos/dcos-k8s-ml-scaffolds .
          docker push hypnosapos/dcos-k8s-ml-scaffolds

workflows:
  version: 2
  build:
    jobs:
    - "docker-release":
        filters:
          branches:
            only: master
